# Configuration Fly.io pour l'API Population & Foyers
app = "population-foyers-api"
primary_region = "cdg"

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"
  DEBUG = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "echo 'Déploiement terminé'"
